#!/usr/bin/env python
# summarize_manual_labels.py

"""
Summarize manually labeled ComVE error-analysis CSV files.

This script reads the four manual taxonomy files generated by
prepare_error_analysis.py:

    manual_taxonomy_taskA_roberta_large_original.csv
    manual_taxonomy_taskB_roberta_large_original.csv
    manual_taxonomy_taskA_hard_cases_original.csv
    manual_taxonomy_taskB_hard_cases_original.csv

It normalizes free-form error_type labels, computes annotation coverage,
error-type distributions, representative examples, and writes Markdown /
LaTeX summary artifacts.

Usage:
    python src/error_analysis/summarize_manual_labels.py \
        --input_dir outputs/error_analysis \
        --output_dir outputs/error_analysis/manual_summary
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd


# ======== Path Setup ========

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))   # project/src/error_analysis
SRC_DIR = os.path.dirname(CURRENT_DIR)                     # project/src
PROJECT_DIR = os.path.dirname(SRC_DIR)                     # project

sys.path.append(SRC_DIR)

from data_utils import resolve_project_path


# ======== Label Definitions ========

ERROR_TYPE_ORDER = [
    "physical",
    "object_affordance",
    "social",
    "temporal",
    "causal",
    "numerical",
    "lexical_distractor",
    "ambiguity",
    "dataset_noise",
    "other",
]

DISPLAY_NAMES = {
    "physical": "Physical",
    "object_affordance": "Object affordance",
    "social": "Social",
    "temporal": "Temporal",
    "causal": "Causal",
    "numerical": "Numerical",
    "lexical_distractor": "Lexical distractor",
    "ambiguity": "Ambiguity",
    "dataset_noise": "Dataset noise",
    "other": "Other",
}

LABEL_ALIASES = {
    "physical": "physical",
    "physics": "physical",
    "physical constraint": "physical",
    "physical constraints": "physical",
    "physical feasibility": "physical",

    "object": "object_affordance",
    "object affordance": "object_affordance",
    "object affordances": "object_affordance",
    "object_affordance": "object_affordance",
    "affordance": "object_affordance",

    "social": "social",
    "social norm": "social",
    "social norms": "social",
    "pragmatic": "social",
    "human behavior": "social",

    "temporal": "temporal",
    "time": "temporal",
    "duration": "temporal",
    "before after": "temporal",

    "causal": "causal",
    "cause": "causal",
    "causality": "causal",
    "cause effect": "causal",

    "numerical": "numerical",
    "numeric": "numerical",
    "number": "numerical",
    "quantity": "numerical",
    "scale": "numerical",

    "lexical": "lexical_distractor",
    "lexical distractor": "lexical_distractor",
    "lexical_distractor": "lexical_distractor",
    "surface": "lexical_distractor",
    "surface cue": "lexical_distractor",
    "surface cues": "lexical_distractor",

    "ambiguity": "ambiguity",
    "ambiguous": "ambiguity",
    "multiple valid": "ambiguity",
    "multiple_valid": "ambiguity",
    "multiple plausible": "ambiguity",

    "dataset noise": "dataset_noise",
    "dataset_noise": "dataset_noise",
    "noise": "dataset_noise",
    "label noise": "dataset_noise",
    "wrong label": "dataset_noise",
    "bad label": "dataset_noise",

    "other": "other",
}

GROUPS = [
    {
        "key": "taskA_roberta",
        "label": "Task A RoBERTa-large errors",
        "short_label": "A RoBERTa",
        "task": "A",
        "sample_kind": "roberta_large_errors",
        "filename": "manual_taxonomy_taskA_roberta_large_original.csv",
    },
    {
        "key": "taskB_roberta",
        "label": "Task B RoBERTa-large errors",
        "short_label": "B RoBERTa",
        "task": "B",
        "sample_kind": "roberta_large_errors",
        "filename": "manual_taxonomy_taskB_roberta_large_original.csv",
    },
    {
        "key": "taskA_hard",
        "label": "Task A hard cases",
        "short_label": "A hard",
        "task": "A",
        "sample_kind": "hard_cases",
        "filename": "manual_taxonomy_taskA_hard_cases_original.csv",
    },
    {
        "key": "taskB_hard",
        "label": "Task B hard cases",
        "short_label": "B hard",
        "task": "B",
        "sample_kind": "hard_cases",
        "filename": "manual_taxonomy_taskB_hard_cases_original.csv",
    },
]


# ======== Basic Utilities ========

def normalize_text(value) -> str:
    if value is None:
        return ""
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip())


def normalize_error_type(value) -> Optional[str]:
    raw = normalize_text(value).lower()

    if raw == "":
        return None

    if raw in {"nan", "none", "null", "n/a", "na"}:
        return None

    # If someone writes "physical; causal", use the first label as primary.
    for sep in [";", ",", "|"]:
        if sep in raw:
            raw = raw.split(sep)[0].strip()
            break

    raw = raw.replace("-", " ")
    raw = raw.replace("_", " ")
    raw = raw.replace("/", " ")
    raw = re.sub(r"\s+", " ", raw).strip()

    if raw in LABEL_ALIASES:
        return LABEL_ALIASES[raw]

    compact = raw.replace(" ", "_")

    if compact in LABEL_ALIASES:
        return LABEL_ALIASES[compact]

    return "other"


def normalize_noise_flag(value) -> str:
    raw = normalize_text(value).lower()

    if raw in {"yes", "y", "true", "1", "dataset_noise", "noise"}:
        return "yes"

    if raw in {"no", "n", "false", "0"}:
        return "no"

    return ""


def resolve_path(path: str) -> Path:
    return Path(resolve_project_path(path, must_exist=False))


def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def escape_markdown_cell(value) -> str:
    text = normalize_text(value)
    text = text.replace("|", "\\|")
    text = text.replace("\n", " ")
    return text


def markdown_table(rows: List[Dict], columns: List[Tuple[str, str]]) -> str:
    if not rows:
        return "_No rows._"

    headers = [label for _, label in columns]
    keys = [key for key, _ in columns]

    lines = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for row in rows:
        values = [escape_markdown_cell(row.get(key, "")) for key in keys]
        lines.append("| " + " | ".join(values) + " |")

    return "\n".join(lines)


# ======== Loading ========

def read_group(input_dir: Path, group: Dict, allow_missing: bool = False) -> pd.DataFrame:
    path = input_dir / group["filename"]

    if not path.exists():
        if allow_missing:
            print(f"[Warning] Missing file, skipped: {path}")
            return pd.DataFrame()
        raise FileNotFoundError(f"Missing manual taxonomy file: {path}")

    df = pd.read_csv(path, encoding="utf-8-sig", dtype=str)
    df = df.fillna("")

    for col in ["error_type", "secondary_error_type", "is_dataset_noise", "notes"]:
        if col not in df.columns:
            df[col] = ""

    df["analysis_group"] = group["key"]
    df["analysis_group_label"] = group["label"]
    df["analysis_short_label"] = group["short_label"]
    df["task"] = group["task"]
    df["sample_kind"] = group["sample_kind"]
    df["source_file"] = group["filename"]

    df["normalized_error_type"] = df["error_type"].map(normalize_error_type)
    df["normalized_secondary_error_type"] = df["secondary_error_type"].map(normalize_error_type)
    df["normalized_is_dataset_noise"] = df["is_dataset_noise"].map(normalize_noise_flag)

    # If the annotator only marked is_dataset_noise=yes but left error_type empty,
    # count it as dataset_noise.
    mask = (
        df["normalized_error_type"].isna()
        & (df["normalized_is_dataset_noise"] == "yes")
    )
    df.loc[mask, "normalized_error_type"] = "dataset_noise"

    return df


def load_all_groups(input_dir: Path, allow_missing: bool = False) -> pd.DataFrame:
    frames = []

    for group in GROUPS:
        df = read_group(input_dir, group, allow_missing=allow_missing)
        if not df.empty:
            frames.append(df)

    if not frames:
        return pd.DataFrame()

    return pd.concat(frames, ignore_index=True, sort=False)


# ======== Summaries ========

def summarize_groups(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    summary_rows = []
    count_rows = []

    for group in GROUPS:
        if df.empty:
            gdf = pd.DataFrame()
        else:
            gdf = df[df["analysis_group"] == group["key"]].copy()

        total = len(gdf)

        if total > 0:
            annotated = gdf[gdf["normalized_error_type"].notna()].copy()
            annotated_n = len(annotated)
            noise_n = int((gdf["normalized_is_dataset_noise"] == "yes").sum())
            notes_n = int(gdf["notes"].map(lambda x: normalize_text(x) != "").sum())
            counts = annotated["normalized_error_type"].value_counts()
        else:
            annotated = pd.DataFrame()
            annotated_n = 0
            noise_n = 0
            notes_n = 0
            counts = pd.Series(dtype=int)

        unlabeled_n = total - annotated_n
        coverage = annotated_n / total if total else 0.0

        summary_rows.append(
            {
                "group_key": group["key"],
                "group": group["label"],
                "task": group["task"],
                "sample_kind": group["sample_kind"],
                "total_n": total,
                "annotated_n": annotated_n,
                "unlabeled_n": unlabeled_n,
                "coverage": f"{coverage:.4f}",
                "coverage_percent": pct(coverage),
                "dataset_noise_flag_n": noise_n,
                "notes_filled_n": notes_n,
                "source_file": group["filename"],
            }
        )

        for error_type in ERROR_TYPE_ORDER:
            count = int(counts.get(error_type, 0))
            percent = count / annotated_n if annotated_n else 0.0

            count_rows.append(
                {
                    "group_key": group["key"],
                    "group": group["label"],
                    "task": group["task"],
                    "sample_kind": group["sample_kind"],
                    "error_type": error_type,
                    "display_error_type": DISPLAY_NAMES[error_type],
                    "count": count,
                    "percent": f"{percent:.4f}",
                    "percent_display": pct(percent),
                    "annotated_n": annotated_n,
                    "total_n": total,
                    "unlabeled_n": unlabeled_n,
                }
            )

    return pd.DataFrame(summary_rows), pd.DataFrame(count_rows)


def top_types(counts_df: pd.DataFrame, group_key: str, n: int = 3) -> List[Tuple[str, int, float]]:
    rows = counts_df[
        (counts_df["group_key"] == group_key)
        & (counts_df["count"] > 0)
    ].copy()

    if rows.empty:
        return []

    rows["percent_float"] = rows["percent"].astype(float)

    rows = rows.sort_values(
        ["count", "error_type"],
        ascending=[False, True],
    ).head(n)

    return [
        (
            str(row["error_type"]),
            int(row["count"]),
            float(row["percent_float"]),
        )
        for _, row in rows.iterrows()
    ]


def top_type_text(counts_df: pd.DataFrame, group_key: str, n: int = 3) -> str:
    items = top_types(counts_df, group_key, n=n)

    if not items:
        return "none"

    parts = []

    for error_type, count, percent in items:
        parts.append(f"{DISPLAY_NAMES[error_type]} ({count}, {pct(percent)})")

    return "; ".join(parts)


# ======== Representative Examples ========

def select_representative_examples(
    df: pd.DataFrame,
    counts_df: pd.DataFrame,
    max_per_group: int = 3,
) -> pd.DataFrame:
    if df.empty:
        return pd.DataFrame()

    rows = []

    for group in GROUPS:
        group_key = group["key"]
        gdf = df[
            (df["analysis_group"] == group_key)
            & (df["normalized_error_type"].notna())
        ].copy()

        if gdf.empty:
            continue

        candidate_types = [
            error_type
            for error_type, _, _ in top_types(counts_df, group_key, n=max_per_group)
        ]

        if not candidate_types:
            continue

        picked_ids = set()

        for error_type in candidate_types:
            candidates = gdf[gdf["normalized_error_type"] == error_type].copy()

            if candidates.empty:
                continue

            candidates["_note_len"] = candidates["notes"].map(lambda x: len(normalize_text(x)))
            candidates = candidates.sort_values("_note_len", ascending=False)

            picked = candidates.iloc[0]

            row_id = normalize_text(picked.get("id", ""))
            if row_id in picked_ids:
                continue
            picked_ids.add(row_id)

            base = {
                "group_key": group_key,
                "group": group["label"],
                "task": group["task"],
                "sample_kind": group["sample_kind"],
                "id": row_id,
                "error_type": error_type,
                "display_error_type": DISPLAY_NAMES.get(error_type, error_type),
                "secondary_error_type": normalize_text(picked.get("normalized_secondary_error_type", "")),
                "is_dataset_noise": normalize_text(picked.get("normalized_is_dataset_noise", "")),
                "notes": normalize_text(picked.get("notes", "")),
                "gold": normalize_text(picked.get("gold", "")),
                "pred": normalize_text(picked.get("pred", "")),
                "confusion": normalize_text(picked.get("confusion", "")),
                "model_predictions": normalize_text(picked.get("model_predictions", "")),
                "source_file": normalize_text(picked.get("source_file", "")),
            }

            if group["task"] == "A":
                base.update(
                    {
                        "text_summary": (
                            f"S0: {normalize_text(picked.get('sent0', ''))} | "
                            f"S1: {normalize_text(picked.get('sent1', ''))}"
                        ),
                        "gold_text": normalize_text(picked.get("gold_nonsense_sentence", "")),
                        "predicted_text": normalize_text(picked.get("predicted_nonsense_sentence", "")),
                    }
                )
            else:
                base.update(
                    {
                        "text_summary": (
                            f"FalseSent: {normalize_text(picked.get('false_sent', ''))} | "
                            f"A: {normalize_text(picked.get('OptionA', ''))} | "
                            f"B: {normalize_text(picked.get('OptionB', ''))} | "
                            f"C: {normalize_text(picked.get('OptionC', ''))}"
                        ),
                        "gold_text": normalize_text(picked.get("gold_option", "")),
                        "predicted_text": normalize_text(picked.get("predicted_option", "")),
                    }
                )

            rows.append(base)

    return pd.DataFrame(rows)


# ======== Plotting ========

def plot_distribution(
    counts_df: pd.DataFrame,
    summary_df: pd.DataFrame,
    output_path: Path,
) -> bool:
    try:
        import matplotlib.pyplot as plt
        from matplotlib.ticker import FuncFormatter
    except ImportError:
        print("[Warning] matplotlib is not installed. Skipping plot.")
        return False

    if counts_df.empty:
        print("[Warning] Empty counts table. Skipping plot.")
        return False

    plot_df = counts_df.copy()
    plot_df["percent_float"] = plot_df["percent"].astype(float)

    pivot = plot_df.pivot_table(
        index="group_key",
        columns="error_type",
        values="percent_float",
        aggfunc="first",
        fill_value=0.0,
    )

    group_order = [g["key"] for g in GROUPS]
    pivot = pivot.reindex(group_order).fillna(0.0)

    if pivot.to_numpy().sum() == 0:
        print("[Warning] No annotated labels found. Skipping plot.")
        return False

    summary_by_group = {
        row["group_key"]: row
        for _, row in summary_df.iterrows()
    }

    y_labels = []

    for group in GROUPS:
        row = summary_by_group.get(group["key"], {})
        annotated_n = row.get("annotated_n", 0)
        total_n = row.get("total_n", 0)
        y_labels.append(f"{group['short_label']}\n(n={annotated_n}/{total_n})")

    fig, ax = plt.subplots(figsize=(10, 4.8))

    left = [0.0] * len(y_labels)

    for error_type in ERROR_TYPE_ORDER:
        if error_type not in pivot.columns:
            continue

        values = pivot[error_type].tolist()

        if sum(values) == 0:
            continue

        ax.barh(
            y_labels,
            values,
            left=left,
            label=DISPLAY_NAMES[error_type],
        )

        left = [l + v for l, v in zip(left, values)]

    ax.set_xlim(0, 1)
    ax.set_xlabel("Percentage of manually annotated errors")
    ax.set_title("Manual Error Type Distribution")
    ax.xaxis.set_major_formatter(FuncFormatter(lambda x, _: f"{int(x * 100)}%"))
    ax.legend(
        loc="lower center",
        bbox_to_anchor=(0.5, -0.45),
        ncol=4,
        frameon=False,
    )

    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)

    return True


# ======== Markdown / LaTeX Writers ========

def write_markdown(
    summary_df: pd.DataFrame,
    counts_df: pd.DataFrame,
    examples_df: pd.DataFrame,
    output_path: Path,
):
    coverage_rows = summary_df.to_dict("records")

    count_rows = counts_df[counts_df["count"] > 0].copy()
    count_rows = count_rows.sort_values(
        ["group_key", "count", "error_type"],
        ascending=[True, False, True],
    ).to_dict("records")

    lines = [
        "# Manual Error Analysis Summary",
        "",
        "This file summarizes the manually annotated error taxonomy files.",
        "",
        "Only rows with a filled `error_type` are counted as annotated. "
        "If `is_dataset_noise=yes` is filled while `error_type` is empty, "
        "the row is counted as `dataset_noise`.",
        "",
        "## Annotation Coverage",
        "",
        markdown_table(
            coverage_rows,
            [
                ("group", "Group"),
                ("total_n", "Total"),
                ("annotated_n", "Annotated"),
                ("unlabeled_n", "Unlabeled"),
                ("coverage_percent", "Coverage"),
                ("dataset_noise_flag_n", "Noise flags"),
                ("notes_filled_n", "Notes filled"),
            ],
        ),
        "",
        "## Top Error Types",
        "",
    ]

    for group in GROUPS:
        lines.append(f"- **{group['label']}**: {top_type_text(counts_df, group['key'])}")

    lines.extend(
        [
            "",
            "## Error-Type Distribution",
            "",
            markdown_table(
                count_rows,
                [
                    ("group", "Group"),
                    ("display_error_type", "Error type"),
                    ("count", "Count"),
                    ("percent_display", "Percent"),
                    ("annotated_n", "Annotated N"),
                    ("total_n", "Total N"),
                ],
            ),
            "",
            "## Representative Examples",
            "",
        ]
    )

    if examples_df.empty:
        lines.append("_No representative examples available._")
    else:
        lines.append(
            markdown_table(
                examples_df.to_dict("records"),
                [
                    ("group", "Group"),
                    ("id", "ID"),
                    ("display_error_type", "Error type"),
                    ("gold", "Gold"),
                    ("pred", "Pred"),
                    ("confusion", "Confusion"),
                    ("text_summary", "Text"),
                    ("notes", "Notes"),
                ],
            )
        )

    lines.extend(
        [
            "",
            "## Interpretation Guide",
            "",
            "- `physical`: size, weight, material, space, body, or physical feasibility.",
            "- `object_affordance`: what an object can or cannot be used for.",
            "- `social`: human behavior, social norms, roles, or intentions.",
            "- `temporal`: ordering, duration, frequency, or time-related contradiction.",
            "- `causal`: cause-effect relation is implausible, missing, or reversed.",
            "- `numerical`: quantity, scale, distance, age, money, or count.",
            "- `lexical_distractor`: surface words are similar and a small lexical change decides plausibility.",
            "- `ambiguity`: multiple readings or multiple options are plausible.",
            "- `dataset_noise`: gold answer seems wrong, weak, or ill-formed.",
            "- `other`: does not clearly fit the above categories.",
            "",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")

# ======== Output ========
def save_outputs(
    df: pd.DataFrame,
    summary_df: pd.DataFrame,
    counts_df: pd.DataFrame,
    examples_df: pd.DataFrame,
    output_dir: Path,
    figure_path: Path,
    skip_plot: bool,
):
    ensure_dir(output_dir)

    normalized_path = output_dir / "manual_error_labels_normalized.csv"
    coverage_path = output_dir / "annotation_coverage.csv"
    distribution_path = output_dir / "error_type_distribution.csv"
    examples_path = output_dir / "representative_error_examples.csv"
    markdown_path = output_dir / "manual_error_analysis_summary.md"

    df_out = df.copy()

    for col in ["normalized_error_type", "normalized_secondary_error_type"]:
        if col in df_out.columns:
            df_out[col] = df_out[col].fillna("")

    df_out.to_csv(normalized_path, index=False, encoding="utf-8-sig")
    summary_df.to_csv(coverage_path, index=False, encoding="utf-8-sig")
    counts_df.to_csv(distribution_path, index=False, encoding="utf-8-sig")
    examples_df.to_csv(examples_path, index=False, encoding="utf-8-sig")

    if not skip_plot:
        plotted = plot_distribution(
            counts_df=counts_df,
            summary_df=summary_df,
            output_path=figure_path,
        )

        if plotted:
            print(f"Saved figure to: {figure_path}")

    write_markdown(
        summary_df=summary_df,
        counts_df=counts_df,
        examples_df=examples_df,
        output_path=markdown_path,
    )

    print(f"Saved normalized labels to: {normalized_path}")
    print(f"Saved annotation coverage to: {coverage_path}")
    print(f"Saved error-type distribution to: {distribution_path}")
    print(f"Saved representative examples to: {examples_path}")
    print(f"Saved Markdown summary to: {markdown_path}")

# ======== CLI ========
def parse_args():
    parser = argparse.ArgumentParser(description="Summarize manual ComVE error labels.")

    parser.add_argument(
        "--input_dir",
        type=str,
        default="outputs/error_analysis",
        help="Directory containing manual_taxonomy_*.csv files.",
    )

    parser.add_argument(
        "--output_dir",
        type=str,
        default="outputs/error_analysis/manual_summary",
        help="Directory where summary artifacts will be saved.",
    )

    parser.add_argument(
        "--figure_path",
        type=str,
        default=None,
        help="Path for the generated error-type distribution image.",
    )

    parser.add_argument(
        "--allow_missing",
        action="store_true",
        help="Skip missing manual taxonomy files instead of raising an error.",
    )

    parser.add_argument(
        "--skip_plot",
        action="store_true",
        help="Skip generating the figure image.",
    )

    parser.add_argument(
        "--max_examples_per_group",
        type=int,
        default=3,
        help="Number of representative examples selected per group.",
    )

    return parser.parse_args()



def main():
    args = parse_args()

    input_dir = resolve_path(args.input_dir)
    output_dir = resolve_path(args.output_dir)

    if args.figure_path is None:
        figure_path = output_dir / "fig_error_type_distribution.png"
    else:
        figure_path = resolve_path(args.figure_path)

    print("=" * 60)
    print("Summarizing manual error labels")
    print("=" * 60)
    print(f"Input dir:  {input_dir}")
    print(f"Output dir: {output_dir}")
    print(f"Figure:     {figure_path}")
    print("=" * 60)

    df = load_all_groups(
        input_dir=input_dir,
        allow_missing=args.allow_missing,
    )

    if df.empty:
        raise RuntimeError(
            "No manual taxonomy rows were loaded. "
            "Check --input_dir or run prepare_error_analysis.py first."
        )

    summary_df, counts_df = summarize_groups(df)
    examples_df = select_representative_examples(
        df=df,
        counts_df=counts_df,
        max_per_group=args.max_examples_per_group,
    )

    save_outputs(
        df=df,
        summary_df=summary_df,
        counts_df=counts_df,
        examples_df=examples_df,
        output_dir=output_dir,
        figure_path=figure_path,
        skip_plot=args.skip_plot,
    )

    print("=" * 60)
    print("Done")
    print("=" * 60)
    print(summary_df.to_string(index=False))


if __name__ == "__main__":
    main()
